# Generated by Django 5.1.4 on 2025-04-29 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_created_by_product_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_manager', to='inventory.store'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_staff', to='inventory.store'),
        ),
    ]
